### ISSUE TITLE
Some initial proof-reading for the guide.

### ISSUE THREAD

**Issue by tars003** [IIITBhopal/MetaData#8]
The document was just fine and really just needed a very few small changes.  @tars003

**Comment by Suraj-Upadhyay** [comment]
Thanks @tars003 .
You may submit a pull request and link this issue to it once you have made all your changes.

Regards,
MrSquanchee

**Comment by Suraj-Upadhyay** [comment]
And please read issue #4 to see if you want to solve the same issue or your issue is different ??
Give reasons for your judgement.

Regards,
MrSquanchee

**Comment by tars003** [comment]
Sorry, I did not noticed but most of my changes were already addressed by #4
